### ISSUE TITLE
Permitir mais de uma CC-e para a mesma NF-e

### ISSUE THREAD

**Issue by cristiano-borges** [fincatto/nfe#33]
Melhorar o "WSFacade.corrigeNota" para que possa enviar mais de uma Carta de Correção Eletrônica para a mesma NF-e.
Criar o parâmetro "numeroSequencialEvento" no método "corrigeNota" para que possa ser informado o número sequencial da correção e assim não ocorra erro ao enviar outras CC-e para a mesma NF-e.

**Comment by cristiano-borges** [comment]
alterar o seguinte:

> WSFacade.java

...
    public NFEnviaEventoRetorno corrigeNota(final String chaveDeAcesso, final String textoCorrecao, final int numeroSequencialCorrecao) throws Exception {
        return this.wsCartaCorrecao.corrigeNota(chaveDeAcesso, textoCorrecao, numeroSequencialCorrecao);
...

> WSCartaCorrecao

...
    public NFEnviaEventoRetorno corrigeNota(final String chaveAcesso, final String textoCorrecao, final int numeroSequencialCorrecao) throws Exception {
        final String cartaCorrecaoXML = this.gerarDadosCartaCorrecao(chaveAcesso, textoCorrecao, numeroSequencialCorrecao).toString();
...

...
    private NFEnviaEventoCartaCorrecao gerarDadosCartaCorrecao(final String chaveAcesso, final String textoCorrecao, final int numeroSequencialCorrecao) {
...
        infoEvento.setId(String.format("ID%s%s0%d", WSCartaCorrecao.EVENTO_CARTA_CORRECAO, chaveAcesso, numeroSequencialCorrecao));
        infoEvento.setNumeroSequencialEvento(numeroSequencialCorrecao);
...

**Comment by jefperito** [comment]
Obrigado pela informação. Ajudasse a tornar essa lib melhor :)
:+1:
