### ISSUE TITLE
Justificativa Entrada Contigencia

### ISSUE THREAD

**Issue by rodsnjr** [fincatto/nfe#47]
Qual a forma correta de informar esse valor?

Eu informei o valor gerado no FabricaDeObjetos fake, pois o parse do SEFAZ não está deixando ele passar em branco ...

```exception
Nao foi possivel parsear o xml: cvc-complex-type.2.4.b: O conteúdo do elemento 'ide' não está completo. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":xJust}'.
```

Porém, quando eu mando com tipo de Emissão Normal, o Web Service me retorna que não deve ser informado essa Justificativa de Entrada de Contigencia.

Como eu posso informar um valor que não deve ser informado ?!

Os XSD estão atualizados com a API, e com os ultimos Schemas liberados pelo SEFAZ. Pra versão 3.10.

**Comment by jefperito** [comment]
A biblioteca atualmente não suporta contigência, apenas emissão normal.

**Comment by rodsnjr** [comment]
Acho que ficou âmbigua minha questão.

Estou geralmente emissão normal.
A questão é que acontece o erro mostrado, se eu não informar o valor de contingencia na NFE, de forma que ele não passe pelo PARSE do XSD.

Ao informá-lo em emissão normal, o Web Service do RS / SEFAZ me retorna um erro, dizendo que em Emissão  Normal, não deve ser INFORMADO o valor de contigencia.

**Comment by jefperito** [comment]
Informar um valor que não deve ser informado? basta deixa-lo nulo, nao sete valor no objeto

**Comment by rodsnjr** [comment]
Fazer algo tipo, 

notaInfo.setJustificativaEntradaContigencia(null); ?

tentarei aqui!

**Comment by jefperito** [comment]
Nao... Apenas nao setar nada, apague isso e rode

**Comment by rodsnjr** [comment]
Eu não estou setando nada, e está me dando o erro

Nao foi possivel parsear o xml: cvc-complex-type.2.4.b: O conteúdo do elemento 'ide' não está completo. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":xJust}'.

**Comment by jefperito** [comment]
Voce ta setando tpEmis = 1 (emissao normal)?

na documentacao está o seguinte:

```
Se informada a TAG de tpEmis = 1:
dhCont e xJust não devem ser informados
```

**Comment by rodsnjr** [comment]
Sim, está assim
```java

identificacao.setTipoEmissao(NFTipoEmissao.EMISSAO_NORMAL);
		
if (!identificacao.getTipoEmissao().equals(NFTipoEmissao.EMISSAO_NORMAL))			         identificacao.setJustificativaEntradaContingencia
(NfeFactory.getJustificativaEntradaContigencia());
```

**Comment by jefperito** [comment]
Sim, sugiro você revisar o teu fluxo e verificar o XML gerado.
