### ISSUE TITLE
Geração de Campos fechados.

### ISSUE THREAD

**Issue by rodsnjr** [fincatto/nfe#49]
Estou precisando gerar a NFE com alguns campos vázios.

``` 
<campo/>
``` 

O parser não está aceitando 

```
<campo></campo> 
```

Meu cliente está gerando a XML com o campo

```<cEAN/>``` e o gerador de NFE dele está passando.

Tentei setar o valor para .setCodigoDeBarras(""), ou setCodigoDeBarras(null) ...

No envio de lote o cEAN desaparece em ambos os casos.

**Comment by rodsnjr** [comment]
Encontrei o problema, parece que quando o objeto é reparseado de String para NFNota os campos 

```
<cEAN></cEAN>
```

O campo vázio simplesmente some!

**Comment by jefperito** [comment]
Ele remove por que considera nulo ou String vazia pro parser é a mesma coisa, elemento vazio ou sem elemento não seria a mesma coisa? ja tentou enviar para o sefaz para verificar o erro?

Validador incorreto? você leu a expressão regular de maneira errada, leia novamente. Verifique que a uma expressão regular é praticamente igual do XSD.
