### ISSUE TITLE
Gerar Jar para projeto Web

### ISSUE THREAD

**Issue by andregui7** [fincatto/nfe#51]
Olá, tudo bom?

Estou tendo dificuldades de gerar o Jar do seu projeto pra usar no meu projeto WEB. 

Importei seu projeto Maven no meu Eclipse e executei o "Maven Install", ele não gerou o Jar com os Jar dependentes. Adicionei a tag maven-assembly-plugin no pom.xml, ele gerou o Jar com os Jar dependentes, mas ao executar meu projeto web ele diz "java.lang.ClassNotFoundException: com.fincatto.nfe310.NFeConfig", sendo que o Jar está no meu projeto Web e compila normalmente. 

Será que o Maven está gerando o Jar de forma errada?

Obrigado.

**Comment by jefperito** [comment]
tente esse comando: mvn clean package -U

**Comment by andregui7** [comment]
Consegui fazer usando o Maven no meu projeto Web. Valeu.
