### ISSUE TITLE
NFC-e

### ISSUE THREAD

**Issue by andregui7** [fincatto/nfe#52]
Olá, boa tarde.

Consegui emitir a nota modelo "55" em modo homologação, nota NF-e.

Tentei emitir a NFC-e, atribuindo setModelo("65") e apareceu erro "Modelo da NF-e diferente de 55 Modelo informado: 65".

Consigo emitir nota do tipo 65?

Obrigado.

**Comment by jefperito** [comment]
Olá,

Aqui eu não utilizo NFC-e, mas eu sei que na versão 3.10 os dois layouts ficaram compatíveis (NFC-e e NF-e), então, teoricamente, com essa biblioteca é possível enviar NFC-e.

Lendo a documentação da NFe 3.10 v1.22 na página 16, esse tipo de erro é dado por que tentou comunicar para um endpoint para NF-e, o correto é enviar para um endpoint para NFC-e.

No momento eu não tenho tempo para implementar algo desse tipo, mas eu creio que a criação de um roteamento resolva esse problema e abrange os dois tipos de notas fiscais.

Basicamente seria:

Mapear as urls que o governo disponibiliza para comunicação de NFC-e.
Identificar qual modelo de nota está tentando enviar.
Usar o Endpoint correto no envio.

**Comment by jefperito** [comment]
Caso tu for implementar, quando estiver pronto e funcionando, peço que faça um pull request para a biblioteca para outras pessoas possam se beneficiar do envio de NFC-e também :)

**Comment by andregui7** [comment]
Obrigado, jefperito. Vou tentar adaptar pra NFC-e. Se tiver sucesso eu aviso.

**Comment by andregui7** [comment]
Como você gerou as classes Stub? Provavelmente vou ter que gerar baseado nas URLs do NFC-e. Usou alguma biblioteca específica?

**Comment by jefperito** [comment]
https://github.com/fincatto/nfe/blob/master/docs/stubs_webservice.txt

Eu escrevi esse doc para gerar stubs quando tava montando os stubs para os webservices do governo

**Comment by andregui7** [comment]
Não consigo baixar os wsdl, aparece "Código do erro: sec_error_untrusted_issuer."

**Comment by andregui7** [comment]
Teoricamente seria a URL https://nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3?wsdl para baixar um dos wsdl.

http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=9

**Comment by jefperito** [comment]
hmmm entendi.

Consegui pegar aqui: https://gist.github.com/jefperito/e92e9af8daf2fd6f02e9

**Comment by andregui7** [comment]
Como conseguiu?

**Comment by jefperito** [comment]
eu tenho os certificados assinados nessa maquina q eu utilizo

**Comment by andregui7** [comment]
Bom, gerei a classe Stub, alterei o WSLoteEnvio apontando para a classe gerada NfeAutorizacao3Stub e ao gerar a nota ele retorna:

<retEnviNFe versao="3.10" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>PR-v3_1_1</verAplic><cStat>242</cStat><xMotivo>Cabecalho - Falha no Schema XML</xMotivo><cUF>41</cUF><dhRecbto>2015-08-12T14:14:13-03:00</dhRecbto></retEnviNFe>

Tem alguma sugestão?

**Comment by andregui7** [comment]
Vi que no método enviaLote( tem a linha 
```
final OMElement omElement = this.nfeToOMElement(xml);
```
que aponta para:
```
private OMElement nfeToOMElement(final String documento) throws XMLStreamException {
        final OMElement ome = AXIOMUtil.stringToOM(documento);
        final Iterator<?> children = ome.getChildrenWithLocalName(WSLoteEnvio.NFE_ELEMENTO);
        while (children.hasNext()) {
            final OMElement omElement = (OMElement) children.next();
            if ((omElement != null) && (WSLoteEnvio.NFE_ELEMENTO.equals(omElement.getLocalName()))) {
                omElement.addAttribute("xmlns", NFeConfig.NFE_NAMESPACE, null);
            }
        }
        return ome;
    }
```
Devo alterar essas constantes NFE_ELEMENTO e NFE_NAMESPACE talvez?

**Comment by jefperito** [comment]
Não, se foram integrados, o mesmo xml deve ficar igual... talvez se os metodos do wsdl da NFe e NFCe forem iguais, a parte do stub nao precisa mudar:

WSLoteEnvio.java:44

final NfeAutorizacaoLoteResult autorizacaoLoteResult = new NfeAutorizacaoStub(NFAutorizador31.valueOfCodigoUF(this.config.getCUF()).getNfeAutorizacao(this.config.getAmbiente())).nfeAutorizacaoLote(dados, cabecalhoSOAP);


esse NFAutorizador31.valueOfCodigoUF retorna a UF que vai ser utilizada de acordo com a UF setada no config do usuario da biblioteca...

Talvez criar um novo NFAutorizador31, como NFCAutorizador31 por exemplo, com as urls dos lugares que recebem NFC-e.

dae nesse metodo verificar o modelo...

lote.getNotas().get(0).getInfo().getIdentificacao().getModelo() se for 55 usar o anterior, se for o 65 usar esse novo...

mas isso só vale se as mensagens trocadas pelo wsdl forem iguais ;)

**Comment by andregui7** [comment]
Na classe NFAutorizador31 inseri método public abstract String getNfceAutorizacao(NFAmbiente ambiente); todas as UF tiveram que implementar. No PR ficou:
```
@Override
        public String getNfceAutorizacao(final NFAmbiente ambiente) {
            return NFAmbiente.HOMOLOGACAO.equals(ambiente) ? "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3?wsdl" : "https://nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3?wsdl";
        }
```

**Comment by andregui7** [comment]
Os stubs tem URLs diferentes:

http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao
http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao3

**Comment by andregui7** [comment]
Perito, boas notícias.

Deixei pra lá minha classe Stub, utilizei a mesma do seu projeto (NfeAutorizacaoStub) e só alterei a classe NFAutorizador31, colocando novos métodos (getNfceAutorizacao por exemplo) com a URL de NFC-e do PR (https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3?wsdl) e ele gerou o NFC-e normal. Funcionou! 

O retorno:

```
<retConsReciNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="3.10"><tpAmb>2</tpAmb><verAplic>PR-v3_1_1</verAplic><nRec>411000000185197</nRec><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>41</cUF><dhRecbto>2015-08-13T13:50:02-03:00</dhRecbto><protNFe versao="3.10"><infProt><tpAmb>2</tpAmb><verAplic>PR-v3_1_1</verAplic><chNFe>41150804118412000181650030000000461203789620</chNFe><dhRecbto>2015-08-13T13:49:59-03:00</dhRecbto><digVal>AILxo0BkULfERH5DtqrQTX56eKc=</digVal><cStat>705</cStat><xMotivo>NFC-e com data de entrada/saida</xMotivo></infProt></protNFe></retConsReciNFe>
```
Bom, agora acho que dá pra alterar seu projeto pra receber NFC-e.

E agora? Melhor criar uma classe NFCAutorizador31? Ou criar métodos na classe NFAutorizador31 existente?

**Comment by andregui7** [comment]
Informei o pagamento, que é obrigatório na NFC-e e está disparando erro:

```org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1947; cvc-complex-type.2.4.a: Foi detectado um conteúdo inválido começando com o elemento 'pagamentos'. Era esperado um dos '{"http://www.portalfiscal.inf.br/nfe":cobr, "http://www.portalfiscal.inf.br/nfe":pag, "http://www.portalfiscal.inf.br/nfe":infAdic, "http://www.portalfiscal.inf.br/nfe":exporta, "http://www.portalfiscal.inf.br/nfe":compra, "http://www.portalfiscal.inf.br/nfe":cana}'.```

Realmente está imprimindo o XML de forma incorreta, está imprimindo uma tag <pagamentos ao invés de só a tag <pag>:
```<pagamentos class="java.util.Arrays$ArrayList"><pag><tPag>01</tPag><vPag>12.00</vPag></pag></pagamentos>```

**Comment by andregui7** [comment]
Tá faltando inline = true na annotation @ElementList no atributo pagamentos da classe NFNotaInfo.

**Comment by imktec** [comment]
Pessoal estou com um sistema web que só está faltando a emissão de nota, já
tenho 3 clientes,

quem quiser me ajudar a gente pode fazer uma sociedade, segue meu e-mail
isantos.ads@gmail.com

Em 11 de agosto de 2015 18:19, andregui7 <notifications@github.com>
escreveu:

**Comment by fincatto** [comment]
Olá Andre. 
Você consegue criar ao menos um teste unitário e fazer um pull request dessa sua alteração?
Assim outros colegas poderão se beneficiar do seu trabalho.
[]s

**Comment by andregui7** [comment]
Faço sim, o que seria melhor será? Criar uma classe NFCAutorizador31? Ou criar métodos na classe NFAutorizador31 existente? Tanto faz?

**Comment by fincatto** [comment]
Se a alteração vale para ambas as notas, o que creio ser verdade, as alterações de código devem ser feitas na classe NFAutorizador31.
Já os testes, por sua vez, devem ficar em suas classes próprias, conforme o padrão do projeto (veja demais classes de teste).
Att,
Diego
