### ISSUE TITLE
Atualização dos Endereços dos Servidores

### ISSUE THREAD

**Issue by rodsnjr** [fincatto/nfe#58]
Olá, parece que a SEFAZ do RS está atualizando os endereços servidores.

Acredito que será necessário atualizar os arquivos de comunicação com o servidores na API.

https://www.sefaz.rs.gov.br/Site/NoticiaDetalhes.aspx?NoticiaId=5491

também em:

http://www.javac.com.br/jc/posts/list/2166-novos-ambientes-de-autorizacao-de-documentos-fiscais-nfe-nfce-cte-e-mdfe.page

**Comment by fincatto** [comment]
Foi lançado um novo release com as urls atualizadas:
https://github.com/fincatto/nfe/releases/tag/1.0.7

**Comment by rodsnjr** [comment]
Opa, já atualizei aqui, muito grato pela compreensão :+1:
