### ISSUE TITLE
campo "impostoDevol" em "det" não existe

### ISSUE THREAD

**Issue by xnog** [fincatto/nfe#8]
O campo "impostoDevol" que fica abaixo de "det", no XML da nota, não está na classe NFNotaInfoItem. É um campo novo da nota fiscal 3.10. Existe algum motivo para não estar lá, ou é um bug?

Obrigado.

**Comment by jefperito** [comment]
Irei verificar aqui de acordo com a documentação da 3.10, caso esteja incoerente, eu corrigo,

Obrigado pelo feedback

**Comment by jefperito** [comment]
Problema corrigido.
